/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframe;

import conn.JavaConnectDBROLE;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author rimsh
 */
public class DistributorRecord extends javax.swing.JFrame {
   
    /**
     * Creates new form DistributorJframe
     */
    public DistributorRecord() {
        initComponents();
         Updated_Table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        DistributorTitle = new javax.swing.JLabel();
        DistributorRecordTitle = new javax.swing.JLabel();
        DistributorId = new javax.swing.JLabel();
        DistributorNAME = new javax.swing.JLabel();
        DistributorEMAIL = new javax.swing.JLabel();
        DistributorID = new javax.swing.JTextField();
        DistributorName = new javax.swing.JTextField();
        DistributorEmail = new javax.swing.JTextField();
        DistributorAddBtn = new javax.swing.JButton();
        DistributorUpdateBtn = new javax.swing.JButton();
        DistributorTable = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        DistributorCNINC = new javax.swing.JLabel();
        DistributorNIC = new javax.swing.JTextField();
        DistributorPHONE = new javax.swing.JLabel();
        DistributorPhone = new javax.swing.JTextField();
        DistributorLogoutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel3.setLayout(null);

        DistributorTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        DistributorTitle.setForeground(new java.awt.Color(0, 102, 102));
        DistributorTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DistributorTitle.setText("Distrubutor");
        jPanel3.add(DistributorTitle);
        DistributorTitle.setBounds(90, 50, 210, 50);

        DistributorRecordTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        DistributorRecordTitle.setForeground(new java.awt.Color(0, 102, 102));
        DistributorRecordTitle.setText("Distrubutor");
        jPanel3.add(DistributorRecordTitle);
        DistributorRecordTitle.setBounds(660, 90, 220, 30);

        DistributorId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DistributorId.setForeground(new java.awt.Color(0, 102, 102));
        DistributorId.setText("ID");
        jPanel3.add(DistributorId);
        DistributorId.setBounds(70, 170, 19, 22);

        DistributorNAME.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DistributorNAME.setForeground(new java.awt.Color(0, 102, 102));
        DistributorNAME.setText("Name");
        jPanel3.add(DistributorNAME);
        DistributorNAME.setBounds(40, 270, 90, 22);

        DistributorEMAIL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DistributorEMAIL.setForeground(new java.awt.Color(0, 102, 102));
        DistributorEMAIL.setText("Email");
        jPanel3.add(DistributorEMAIL);
        DistributorEMAIL.setBounds(40, 330, 90, 22);
        jPanel3.add(DistributorID);
        DistributorID.setBounds(150, 160, 170, 30);
        jPanel3.add(DistributorName);
        DistributorName.setBounds(150, 260, 170, 30);

        DistributorEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistributorEmailActionPerformed(evt);
            }
        });
        jPanel3.add(DistributorEmail);
        DistributorEmail.setBounds(150, 320, 170, 30);

        DistributorAddBtn.setBackground(new java.awt.Color(0, 102, 102));
        DistributorAddBtn.setForeground(new java.awt.Color(255, 255, 255));
        DistributorAddBtn.setText("ADD");
        DistributorAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistributorAddBtnActionPerformed(evt);
            }
        });
        jPanel3.add(DistributorAddBtn);
        DistributorAddBtn.setBounds(40, 530, 100, 40);

        DistributorUpdateBtn.setBackground(new java.awt.Color(0, 102, 102));
        DistributorUpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        DistributorUpdateBtn.setText("Update");
        DistributorUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistributorUpdateBtnActionPerformed(evt);
            }
        });
        jPanel3.add(DistributorUpdateBtn);
        DistributorUpdateBtn.setBounds(160, 530, 100, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        DistributorTable.setViewportView(jTable1);

        jPanel3.add(DistributorTable);
        DistributorTable.setBounds(490, 160, 550, 400);

        DistributorCNINC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DistributorCNINC.setForeground(new java.awt.Color(0, 102, 102));
        DistributorCNINC.setText("CNIC");
        jPanel3.add(DistributorCNINC);
        DistributorCNINC.setBounds(60, 210, 60, 22);
        jPanel3.add(DistributorNIC);
        DistributorNIC.setBounds(150, 210, 170, 30);

        DistributorPHONE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DistributorPHONE.setForeground(new java.awt.Color(0, 102, 102));
        DistributorPHONE.setText("Phone Number");
        jPanel3.add(DistributorPHONE);
        DistributorPHONE.setBounds(20, 380, 120, 22);
        jPanel3.add(DistributorPhone);
        DistributorPhone.setBounds(160, 380, 170, 30);

        DistributorLogoutBtn.setBackground(new java.awt.Color(255, 255, 204));
        DistributorLogoutBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DistributorLogoutBtn.setForeground(new java.awt.Color(0, 102, 102));
        DistributorLogoutBtn.setText("Logout");
        DistributorLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistributorLogoutBtnActionPerformed(evt);
            }
        });
        jPanel3.add(DistributorLogoutBtn);
        DistributorLogoutBtn.setBounds(1060, 320, 110, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1366, 768);

        setSize(new java.awt.Dimension(1211, 683));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     public void connection (Connection connection) throws ClassNotFoundException{ //establishing conncetion with oracle
        
       // This function is for creating connection with oracle database
        
        try {
            Class.forName("oracle.jdbc.OracleDriver"); // defining the oracle driver 
             connection = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:rimsha", "rimsha", "rimsha"); // establishing connection with user in orcale database
        } 
        
        catch (SQLException ex) { // throwing exception if thus user is not available
            
            Logger.getLogger(ComplainsRecord.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    private void DistributorEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistributorEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DistributorEmailActionPerformed

    private void DistributorAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistributorAddBtnActionPerformed
// adding data from texfield into database table columns
        
        try{
       Connection connection = null;
       connection(connection);
        String sql="insert into DISTRIBUTORS"+"(DIS_ID,DIS_NAME,DIS_EMAILADDRESS,DIS_PHONE,DIS_CNIC)"+"values(?,?,?,?,?)";
        PreparedStatement preparedstatement =connection.prepareStatement(sql);
        int a=(int) Integer.parseInt(DistributorID.getText());
        
       preparedstatement.setInt(1, a);
       preparedstatement.setString(2, DistributorName.getText());
        preparedstatement.setString(3, DistributorEmail.getText());
        preparedstatement.setString(4, DistributorPhone.getText());
        preparedstatement.setString(5, DistributorNIC.getText());
        preparedstatement.executeUpdate();
        JOptionPane.showMessageDialog(this,"Successfully Inserted!");
       }
       catch(Exception e)
       {JOptionPane.showMessageDialog(this,e.getMessage());
       }
        
 Updated_Table();
    }//GEN-LAST:event_DistributorAddBtnActionPerformed

    
    
    
    
      public void Updated_Table() // updating table in Jframe
{
    try{
       Connection connection = null;
       connection(connection);
        String sql="Select * from DISTRIBUTORS";
        PreparedStatement  preparedstatement=null;
        preparedstatement=connection.prepareStatement(sql);
        ResultSet resultset=null;
        resultset= preparedstatement.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(resultset));
      
       }
       catch(Exception e)
       {JOptionPane.showMessageDialog(this,e.getMessage());
       }  
}
    
    
    
    
    
    
    private void DistributorUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistributorUpdateBtnActionPerformed
// updating data from texfield into database table columns
        
         try{
        Connection connection = null;
       connection(connection);
        String sql="Update DISTRIBUTORS set DIS_NAME =?,DIS_EMAILADDRESS=?,DIS_PHONE=?,DIS_CNIC=?"+" where DIS_ID =?";
        PreparedStatement preparedstatement=connection.prepareStatement(sql);
        preparedstatement.setString(1, DistributorName.getText());
        preparedstatement.setString(2, DistributorEmail.getText());
        preparedstatement.setString(3,  DistributorPhone.getText());
        preparedstatement.setString(4, DistributorNIC.getText());
         int a=(int) Integer.parseInt(DistributorID.getText());
        preparedstatement.setInt(5, a);
        preparedstatement.executeUpdate();
        JOptionPane.showMessageDialog(this,"Successfully Updated!");
       }
       catch(Exception e)
       {JOptionPane.showMessageDialog(this,e.getMessage());
       }  
        
         Updated_Table();
    }//GEN-LAST:event_DistributorUpdateBtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

      
    }//GEN-LAST:event_jTable1MouseClicked

    private void DistributorLogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistributorLogoutBtnActionPerformed
// this button is for to visible previous creen and disclose the current screen

         new DistributorVisitorLogin().setVisible(true);
          this.dispose();
        
    }//GEN-LAST:event_DistributorLogoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DistributorRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DistributorRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DistributorRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DistributorRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DistributorRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DistributorAddBtn;
    private javax.swing.JLabel DistributorCNINC;
    private javax.swing.JLabel DistributorEMAIL;
    private javax.swing.JTextField DistributorEmail;
    private javax.swing.JTextField DistributorID;
    private javax.swing.JLabel DistributorId;
    private javax.swing.JButton DistributorLogoutBtn;
    private javax.swing.JLabel DistributorNAME;
    private javax.swing.JTextField DistributorNIC;
    private javax.swing.JTextField DistributorName;
    private javax.swing.JLabel DistributorPHONE;
    private javax.swing.JTextField DistributorPhone;
    private javax.swing.JLabel DistributorRecordTitle;
    private javax.swing.JScrollPane DistributorTable;
    private javax.swing.JLabel DistributorTitle;
    private javax.swing.JButton DistributorUpdateBtn;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
