/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframe;

import conn.JavaConnectDB;
import conn.JavaConnectDBROLE;
import conn.ManagerCustomerLogin;
import java.sql.Connection;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author rimsh
 */
public class DistributorVisitorLogin extends javax.swing.JFrame {

    
     Connection connection = null;
    OraclePreparedStatement preparedstatement = null;
    OracleResultSet resultset = null;
    String username = null;
    String password = null;
    /**
     * Creates new form DVLogin
     */
    public DistributorVisitorLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DistributorUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DistributorLoginBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        DistributorLoginTitle = new javax.swing.JLabel();
        VisitorLoginTitle = new javax.swing.JLabel();
        DistributorPassowrd = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        VisitorUsername = new javax.swing.JTextField();
        VisitorLoginBtn = new javax.swing.JButton();
        LoginAsOtherBtn = new javax.swing.JButton();
        VisitorPassword = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        DistributorBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(DistributorUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 190, 40));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 60, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        DistributorLoginBtn.setBackground(new java.awt.Color(255, 255, 255));
        DistributorLoginBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DistributorLoginBtn.setForeground(new java.awt.Color(0, 102, 102));
        DistributorLoginBtn.setText("LOGIN");
        DistributorLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistributorLoginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(DistributorLoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 140, 50));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DistributorLoginTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        DistributorLoginTitle.setForeground(new java.awt.Color(255, 255, 255));
        DistributorLoginTitle.setText("Distributor Login");
        jPanel2.add(DistributorLoginTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        VisitorLoginTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        VisitorLoginTitle.setForeground(new java.awt.Color(255, 255, 255));
        VisitorLoginTitle.setText("Visitor Login");
        jPanel2.add(VisitorLoginTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 90));
        jPanel1.add(DistributorPassowrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 190, 40));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, -1, -1));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, -1, -1));
        jPanel1.add(VisitorUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 190, 40));

        VisitorLoginBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VisitorLoginBtn.setForeground(new java.awt.Color(0, 102, 102));
        VisitorLoginBtn.setText("Login");
        VisitorLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisitorLoginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(VisitorLoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, 130, 50));

        LoginAsOtherBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LoginAsOtherBtn.setForeground(new java.awt.Color(0, 102, 102));
        LoginAsOtherBtn.setText("Login as others");
        LoginAsOtherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginAsOtherBtnActionPerformed(evt);
            }
        });
        jPanel1.add(LoginAsOtherBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 160, 40));
        jPanel1.add(VisitorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 190, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 102));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 513, 90, 40));

        DistributorBack.setText("Back");
        DistributorBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistributorBackActionPerformed(evt);
            }
        });
        jPanel1.add(DistributorBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 80, 40));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1010, 580);

        setSize(new java.awt.Dimension(939, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DistributorLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistributorLoginBtnActionPerformed
// getiing useranem and password from textfield and checking from data base and login 
        

connection = JavaConnectDB.ConnectDB();
        username= DistributorUsername.getText();
       password=DistributorPassowrd.getText();
        try{
            String sql = "select * from DISLOGIN where username = ? and password = ? ";
            preparedstatement = (OraclePreparedStatement) connection.prepareStatement(sql);
            preparedstatement.setString(1,DistributorUsername.getText());
            preparedstatement.setString(2,DistributorPassowrd.getText());
            
            resultset = (OracleResultSet) preparedstatement.executeQuery();
          
            if(resultset.next())
            {
               JOptionPane.showMessageDialog(null," login successfuly");
               DistributorRecord m= new DistributorRecord();
               m.u = this.username ;
               m.p = this.password;
               this.setVisible(false);
               m.setVisible(true);
               
            }
            else
            {
                 JOptionPane.showMessageDialog(null," invalid login");
            }
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_DistributorLoginBtnActionPerformed

    
    private void VisitorLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisitorLoginBtnActionPerformed
 // getiing useranem and password from textfield and checking from data base and login 
        
        username = VisitorUsername.getText();
password = VisitorPassword.getText();
 try{
     connection = JavaConnectDB.ConnectDB();
            String sql = "select * from VLOGIN where username = ? and password = ? ";
           preparedstatement = (OraclePreparedStatement) connection.prepareStatement(sql);
           preparedstatement.setString(1,username);
           preparedstatement.setString(2,password);
            JOptionPane.showMessageDialog(null," exeqution se pehle");
            resultset = (OracleResultSet) preparedstatement.executeQuery();
           JOptionPane.showMessageDialog(null," exeqution se pehle");
            if(resultset.next() == false)
            {
                 JOptionPane.showMessageDialog(null," login successfuly");
                  VisitorsRecord m= new VisitorsRecord();
               m.u = this.username;
               m.p = this.password;
               this.setVisible(false);
               m.setVisible(true);
               
               
            }
            else
            {
               
               JOptionPane.showMessageDialog(null," invalid login");
                
                
                 
            }
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_VisitorLoginBtnActionPerformed

    private void LoginAsOtherBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginAsOtherBtnActionPerformed
      // this button is for to visible previous creen and disclose the current screen

        new DoctorLogin().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_LoginAsOtherBtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // this button is for to visible previous creen and disclose the current screen
        
        new ManagerCustomerLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void DistributorBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistributorBackActionPerformed
// this button is for to visible previous creen and disclose the current screen
new ManagerCustomerLogin().setVisible(true);
this.dispose();

       
    }//GEN-LAST:event_DistributorBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DistributorVisitorLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DistributorVisitorLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DistributorVisitorLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DistributorVisitorLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DistributorVisitorLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DistributorBack;
    private javax.swing.JButton DistributorLoginBtn;
    private javax.swing.JLabel DistributorLoginTitle;
    private javax.swing.JPasswordField DistributorPassowrd;
    private javax.swing.JTextField DistributorUsername;
    private javax.swing.JButton LoginAsOtherBtn;
    private javax.swing.JButton VisitorLoginBtn;
    private javax.swing.JLabel VisitorLoginTitle;
    private javax.swing.JPasswordField VisitorPassword;
    private javax.swing.JTextField VisitorUsername;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
