/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframe;

import conn.ManagerCustomerLogin;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author rimsh
 */
public class EmployeeRecord extends javax.swing.JFrame {

    /**
     * Creates new form EmployessJframe
     */
    public EmployeeRecord() {
        initComponents();
          Updated_Table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        WorkerTitle = new javax.swing.JLabel();
        WorkerRecordTitle = new javax.swing.JLabel();
        WorkerId = new javax.swing.JLabel();
        WorkerNAME = new javax.swing.JLabel();
        WorkerEMAIL = new javax.swing.JLabel();
        WorkerID = new javax.swing.JTextField();
        WorkerName = new javax.swing.JTextField();
        WorkerEmail = new javax.swing.JTextField();
        WorkerAddBtn = new javax.swing.JButton();
        WorkerUpdateBtn = new javax.swing.JButton();
        WorkerTable = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        WorkerCNIC = new javax.swing.JLabel();
        WorkerNIC = new javax.swing.JTextField();
        WorkerPHONE = new javax.swing.JLabel();
        WorkerPhone = new javax.swing.JTextField();
        WorkerLogoutBtn = new javax.swing.JButton();
        WorkerADDESS = new javax.swing.JLabel();
        WorkerAddres = new javax.swing.JTextField();
        WorkerDeleteBtn = new javax.swing.JButton();
        WorkerCATEGORY = new javax.swing.JLabel();
        WorkerCategoryCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel5.setLayout(null);

        WorkerTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        WorkerTitle.setForeground(new java.awt.Color(0, 102, 102));
        WorkerTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WorkerTitle.setText("Workers");
        jPanel5.add(WorkerTitle);
        WorkerTitle.setBounds(90, 50, 170, 50);

        WorkerRecordTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        WorkerRecordTitle.setForeground(new java.awt.Color(0, 102, 102));
        WorkerRecordTitle.setText("Workers Records");
        jPanel5.add(WorkerRecordTitle);
        WorkerRecordTitle.setBounds(660, 90, 220, 30);

        WorkerId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        WorkerId.setForeground(new java.awt.Color(0, 102, 102));
        WorkerId.setText("ID");
        jPanel5.add(WorkerId);
        WorkerId.setBounds(70, 140, 19, 22);

        WorkerNAME.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        WorkerNAME.setForeground(new java.awt.Color(0, 102, 102));
        WorkerNAME.setText("Name");
        jPanel5.add(WorkerNAME);
        WorkerNAME.setBounds(40, 240, 90, 22);

        WorkerEMAIL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        WorkerEMAIL.setForeground(new java.awt.Color(0, 102, 102));
        WorkerEMAIL.setText("Email");
        jPanel5.add(WorkerEMAIL);
        WorkerEMAIL.setBounds(30, 290, 90, 22);
        jPanel5.add(WorkerID);
        WorkerID.setBounds(140, 140, 170, 30);
        jPanel5.add(WorkerName);
        WorkerName.setBounds(140, 240, 170, 30);

        WorkerEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkerEmailActionPerformed(evt);
            }
        });
        jPanel5.add(WorkerEmail);
        WorkerEmail.setBounds(140, 290, 170, 30);

        WorkerAddBtn.setBackground(new java.awt.Color(0, 102, 102));
        WorkerAddBtn.setForeground(new java.awt.Color(255, 255, 255));
        WorkerAddBtn.setText("ADD");
        WorkerAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkerAddBtnActionPerformed(evt);
            }
        });
        jPanel5.add(WorkerAddBtn);
        WorkerAddBtn.setBounds(20, 560, 100, 40);

        WorkerUpdateBtn.setBackground(new java.awt.Color(0, 102, 102));
        WorkerUpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        WorkerUpdateBtn.setText("Update");
        WorkerUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkerUpdateBtnActionPerformed(evt);
            }
        });
        jPanel5.add(WorkerUpdateBtn);
        WorkerUpdateBtn.setBounds(160, 560, 100, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        WorkerTable.setViewportView(jTable1);

        jPanel5.add(WorkerTable);
        WorkerTable.setBounds(430, 160, 650, 400);

        WorkerCNIC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        WorkerCNIC.setForeground(new java.awt.Color(0, 102, 102));
        WorkerCNIC.setText("CNIC");
        jPanel5.add(WorkerCNIC);
        WorkerCNIC.setBounds(60, 190, 60, 22);
        jPanel5.add(WorkerNIC);
        WorkerNIC.setBounds(140, 190, 170, 30);

        WorkerPHONE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        WorkerPHONE.setForeground(new java.awt.Color(0, 102, 102));
        WorkerPHONE.setText("Phone Number");
        jPanel5.add(WorkerPHONE);
        WorkerPHONE.setBounds(20, 340, 120, 22);
        jPanel5.add(WorkerPhone);
        WorkerPhone.setBounds(140, 340, 170, 30);

        WorkerLogoutBtn.setBackground(new java.awt.Color(255, 255, 204));
        WorkerLogoutBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WorkerLogoutBtn.setForeground(new java.awt.Color(0, 102, 102));
        WorkerLogoutBtn.setText("Logout");
        WorkerLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkerLogoutBtnActionPerformed(evt);
            }
        });
        jPanel5.add(WorkerLogoutBtn);
        WorkerLogoutBtn.setBounds(1100, 330, 110, 40);

        WorkerADDESS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        WorkerADDESS.setForeground(new java.awt.Color(0, 102, 102));
        WorkerADDESS.setText("Address");
        jPanel5.add(WorkerADDESS);
        WorkerADDESS.setBounds(40, 400, 70, 30);
        jPanel5.add(WorkerAddres);
        WorkerAddres.setBounds(140, 400, 170, 30);

        WorkerDeleteBtn.setBackground(new java.awt.Color(0, 102, 102));
        WorkerDeleteBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WorkerDeleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        WorkerDeleteBtn.setText("Delete");
        WorkerDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkerDeleteBtnActionPerformed(evt);
            }
        });
        jPanel5.add(WorkerDeleteBtn);
        WorkerDeleteBtn.setBounds(280, 560, 110, 40);

        WorkerCATEGORY.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        WorkerCATEGORY.setForeground(new java.awt.Color(0, 102, 102));
        WorkerCATEGORY.setText("Category");
        jPanel5.add(WorkerCATEGORY);
        WorkerCATEGORY.setBounds(40, 460, 80, 30);

        WorkerCategoryCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Farm boy", "Tamer", "Supplier", "Distributor", "Guard", " " }));
        jPanel5.add(WorkerCategoryCombo);
        WorkerCategoryCombo.setBounds(140, 460, 170, 40);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 1366, 768);

        setSize(new java.awt.Dimension(1242, 688));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

      public void connection (Connection connection) throws ClassNotFoundException{
        
       // This function is for creating connection with oracle database
        
        try {
            Class.forName("oracle.jdbc.OracleDriver"); // defining the oracle driver 
             connection = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:rimsha", "rimsha", "rimsha"); // establishing connection with user in orcale database
        } 
        
        catch (SQLException ex) { // throwing exception if thus user is not available
            
            Logger.getLogger(ComplainsRecord.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    
    private void WorkerEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkerEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WorkerEmailActionPerformed

    private void WorkerAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkerAddBtnActionPerformed

        try{
       Connection connection = null;
       connection(connection);
        String sql="insert into EMPLOYEES"+"(E_ID,E_NAME,E_CNIC,E_PHONE,E_ADDRESS,E_EMAILADDRESS,CATEGORY)"+"values(?,?,?,?,?,?,?)";
        PreparedStatement preparedstatement=connection.prepareStatement(sql);
        int a=(int) Integer.parseInt(WorkerID.getText());
        
  preparedstatement.setInt(1, a);
 //pst.setString(1, CID2.getText());
         preparedstatement.setString(2, WorkerName.getText());
         preparedstatement.setString(3, WorkerNIC.getText());
         preparedstatement.setString(4, WorkerPhone.getText());
         preparedstatement.setString(5, WorkerAddres.getText());
          preparedstatement.setString(6, WorkerEmail.getText());
          preparedstatement.setString(7, WorkerCategoryCombo.getSelectedItem().toString());
        
         preparedstatement.executeUpdate();
        JOptionPane.showMessageDialog(this,"Successfully Inserted!");
       }
       catch(Exception e)
       {JOptionPane.showMessageDialog(this,e.getMessage());
       }
    
        
     Updated_Table();
        
        
        
    }//GEN-LAST:event_WorkerAddBtnActionPerformed

    private void WorkerUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkerUpdateBtnActionPerformed

        
           try{
       Connection connection = null;
       connection(connection);
        String sql="Update EMPLOYEES set E_NAME =?,E_CNIC=?,E_PHONE=?,E_ADDRESS=?,E_EMAILADDRESS=?,CATEGORY=?"+" where E_ID =?";
        PreparedStatement  preparedstatement=connection.prepareStatement(sql);
        
        
 //pst.setString(1, CID2.getText());
         preparedstatement.setString(1, WorkerName.getText());
         preparedstatement.setString(2, WorkerNIC.getText());
         preparedstatement.setString(3, WorkerPhone.getText());
         preparedstatement.setString(4, WorkerAddres.getText());
          preparedstatement.setString(5, WorkerEmail.getText());
           preparedstatement.setString(6, WorkerCategoryCombo.getSelectedItem().toString());
         int a=(int) Integer.parseInt(WorkerID.getText());
        
  preparedstatement.setInt(7, a);
        
        
        
        
   
         preparedstatement.executeUpdate();
        JOptionPane.showMessageDialog(this,"Successfully Updated!");
       }
       catch(Exception e)
       {JOptionPane.showMessageDialog(this,e.getMessage());
       }  
              
       Updated_Table();
        
        
    }//GEN-LAST:event_WorkerUpdateBtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    
    
    public void Updated_Table()
{
    try{
       Class.forName("oracle.jdbc.OracleDriver");
            Connection connection = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:rimsha", "rimsha", "rimsha");
        String sql="Select * from EMPLOYEES";
        PreparedStatement  preparedstatement=null;
        preparedstatement=connection.prepareStatement(sql);
        ResultSet resultset=null;
        resultset= preparedstatement.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(resultset));
       // int a=(int) Double.parseDouble(dept.getText());
       // pst.setString(1, sname.getText());
       // pst.setString(2, programf.getText());
      //  pst.setInt(3, a);
       // pst.setString(4,sid.getText());
       // pst.executeUpdate();
       // JOptionPane.showMessageDialog(this,"Successfully updated!");
       }
       catch(Exception e)
       {JOptionPane.showMessageDialog(this,e.getMessage());
       }  
}
    
    
    private void WorkerLogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkerLogoutBtnActionPerformed

        new ManagerCustomerLogin().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_WorkerLogoutBtnActionPerformed

    private void WorkerDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkerDeleteBtnActionPerformed


try{
        Class.forName("oracle.jdbc.OracleDriver");
            Connection connection = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:rimsha", "rimsha", "rimsha");
        String sql="delete from EMPLOYEES where E_ID=?";
        PreparedStatement  preparedstatement=connection.prepareStatement(sql);
        int a=(int) Double.parseDouble(WorkerID.getText());
        preparedstatement.setInt(1, a);
         preparedstatement.executeUpdate();
        JOptionPane.showMessageDialog(this,"Successfully Deleted!");
       }
       catch(Exception e)
       {JOptionPane.showMessageDialog(this,e.getMessage());
       }
Updated_Table();
        // TODO add your handling code here:
    }//GEN-LAST:event_WorkerDeleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WorkerADDESS;
    private javax.swing.JButton WorkerAddBtn;
    private javax.swing.JTextField WorkerAddres;
    private javax.swing.JLabel WorkerCATEGORY;
    private javax.swing.JLabel WorkerCNIC;
    private javax.swing.JComboBox<String> WorkerCategoryCombo;
    private javax.swing.JButton WorkerDeleteBtn;
    private javax.swing.JLabel WorkerEMAIL;
    private javax.swing.JTextField WorkerEmail;
    private javax.swing.JTextField WorkerID;
    private javax.swing.JLabel WorkerId;
    private javax.swing.JButton WorkerLogoutBtn;
    private javax.swing.JLabel WorkerNAME;
    private javax.swing.JTextField WorkerNIC;
    private javax.swing.JTextField WorkerName;
    private javax.swing.JLabel WorkerPHONE;
    private javax.swing.JTextField WorkerPhone;
    private javax.swing.JLabel WorkerRecordTitle;
    private javax.swing.JScrollPane WorkerTable;
    private javax.swing.JLabel WorkerTitle;
    private javax.swing.JButton WorkerUpdateBtn;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
