/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframe;

import conn.ManagerCustomerLogin;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author rimsh
 */
public class OrdersRecords extends javax.swing.JFrame {

    /**
     * Creates new form OrdersJframe
     */
    public OrdersRecords() {
        initComponents();
         Updated_Table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        OrderTitle = new javax.swing.JLabel();
        OrderRecordTitle = new javax.swing.JLabel();
        Orderid = new javax.swing.JLabel();
        ProductID = new javax.swing.JLabel();
        OrderQUANTITY = new javax.swing.JLabel();
        OrderID = new javax.swing.JTextField();
        ProductId = new javax.swing.JTextField();
        OrderQuantity = new javax.swing.JTextField();
        OrderAddBtn = new javax.swing.JButton();
        OrderDeleteBtn = new javax.swing.JButton();
        OrderTable = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Customerid = new javax.swing.JLabel();
        CustomerID = new javax.swing.JTextField();
        OrderDATE = new javax.swing.JLabel();
        OrderLogoutBtn = new javax.swing.JButton();
        OrderTIME = new javax.swing.JLabel();
        OrderTime = new javax.swing.JTextField();
        OrderUpdateBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel3.setLayout(null);

        OrderTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        OrderTitle.setForeground(new java.awt.Color(0, 102, 102));
        OrderTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OrderTitle.setText("Order");
        jPanel3.add(OrderTitle);
        OrderTitle.setBounds(90, 50, 170, 50);

        OrderRecordTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        OrderRecordTitle.setForeground(new java.awt.Color(0, 102, 102));
        OrderRecordTitle.setText("Orders record");
        jPanel3.add(OrderRecordTitle);
        OrderRecordTitle.setBounds(660, 90, 220, 30);

        Orderid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Orderid.setForeground(new java.awt.Color(0, 102, 102));
        Orderid.setText("ID");
        jPanel3.add(Orderid);
        Orderid.setBounds(70, 140, 19, 22);

        ProductID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProductID.setForeground(new java.awt.Color(0, 102, 102));
        ProductID.setText("P_ID");
        jPanel3.add(ProductID);
        ProductID.setBounds(40, 240, 90, 22);

        OrderQUANTITY.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OrderQUANTITY.setForeground(new java.awt.Color(0, 102, 102));
        OrderQUANTITY.setText("Quantity");
        jPanel3.add(OrderQUANTITY);
        OrderQUANTITY.setBounds(30, 290, 90, 22);
        jPanel3.add(OrderID);
        OrderID.setBounds(140, 140, 170, 30);
        jPanel3.add(ProductId);
        ProductId.setBounds(140, 240, 170, 30);

        OrderQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderQuantityActionPerformed(evt);
            }
        });
        jPanel3.add(OrderQuantity);
        OrderQuantity.setBounds(140, 290, 170, 30);

        OrderAddBtn.setBackground(new java.awt.Color(0, 102, 102));
        OrderAddBtn.setForeground(new java.awt.Color(255, 255, 255));
        OrderAddBtn.setText("ADD");
        OrderAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderAddBtnActionPerformed(evt);
            }
        });
        jPanel3.add(OrderAddBtn);
        OrderAddBtn.setBounds(20, 560, 100, 40);

        OrderDeleteBtn.setBackground(new java.awt.Color(0, 102, 102));
        OrderDeleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        OrderDeleteBtn.setText("Delete");
        OrderDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderDeleteBtnActionPerformed(evt);
            }
        });
        jPanel3.add(OrderDeleteBtn);
        OrderDeleteBtn.setBounds(160, 560, 100, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        OrderTable.setViewportView(jTable1);

        jPanel3.add(OrderTable);
        OrderTable.setBounds(490, 160, 550, 400);

        Customerid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Customerid.setForeground(new java.awt.Color(0, 102, 102));
        Customerid.setText("C_id");
        jPanel3.add(Customerid);
        Customerid.setBounds(60, 190, 60, 22);
        jPanel3.add(CustomerID);
        CustomerID.setBounds(140, 190, 170, 30);

        OrderDATE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OrderDATE.setForeground(new java.awt.Color(0, 102, 102));
        OrderDATE.setText("Date");
        jPanel3.add(OrderDATE);
        OrderDATE.setBounds(40, 340, 60, 22);

        OrderLogoutBtn.setBackground(new java.awt.Color(255, 255, 204));
        OrderLogoutBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OrderLogoutBtn.setForeground(new java.awt.Color(0, 102, 102));
        OrderLogoutBtn.setText("Logout");
        OrderLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderLogoutBtnActionPerformed(evt);
            }
        });
        jPanel3.add(OrderLogoutBtn);
        OrderLogoutBtn.setBounds(1060, 320, 110, 40);

        OrderTIME.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OrderTIME.setForeground(new java.awt.Color(0, 102, 102));
        OrderTIME.setText("Time");
        jPanel3.add(OrderTIME);
        OrderTIME.setBounds(50, 400, 70, 30);
        jPanel3.add(OrderTime);
        OrderTime.setBounds(140, 400, 170, 30);

        OrderUpdateBtn.setBackground(new java.awt.Color(0, 102, 102));
        OrderUpdateBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        OrderUpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        OrderUpdateBtn.setText("Update");
        OrderUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderUpdateBtnActionPerformed(evt);
            }
        });
        jPanel3.add(OrderUpdateBtn);
        OrderUpdateBtn.setBounds(280, 560, 100, 40);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(1133, 543, 80, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1366, 768);

        setSize(new java.awt.Dimension(1249, 666));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void connection (Connection connection) throws ClassNotFoundException{
        
       // This function is for creating connection with oracle database
        
        try {
            Class.forName("oracle.jdbc.OracleDriver"); // defining the oracle driver 
             connection = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:rimsha", "rimsha", "rimsha"); // establishing connection with user in orcale database
        } 
        
        catch (SQLException ex) { // throwing exception if thus user is not available
            
            Logger.getLogger(ComplainsRecord.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    private void OrderQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrderQuantityActionPerformed

    private void OrderAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderAddBtnActionPerformed

      /*   if(PID.getText().trim().isEmpty() && CID.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(this,"Product key and customer key is mandatory to add!");
        }*/
        
          try{
       Connection connection = null;
       connection(connection);
        String sql="insert into ORDERS"+"(O_ID,P_ID,C_ID,QUANTITY,DATES,TIME)"+"values(?,?,?,?,?,?)";
        PreparedStatement preparedstatement =connection.prepareStatement(sql);
        int a=(int) Integer.parseInt(OrderID.getText());
        
 preparedstatement.setInt(1, a);
 //pst.setString(1, CID2.getText());
        preparedstatement.setString(2, ProductId.getText());
        preparedstatement.setString(3, CustomerID.getText());
        preparedstatement.setString(4, OrderQuantity.getText());
       // preparedstatement.setString(5, ODATECHOOSER.getText());
         preparedstatement.setString(6, OrderTime.getText());
         
        
     //   pst.executeUpdate();
        if(ProductId.getText().trim().isEmpty() && CustomerID.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(this,"Product key and customer key is mandatory to add!");
        }else
        {
             preparedstatement.executeUpdate();
        JOptionPane.showMessageDialog(this,"Successfully Inserted!");
        }
       }
       catch(Exception e)
       {JOptionPane.showMessageDialog(this,e.getMessage());
       }
    
        
     Updated_Table();
        
        
        
        
        
    }//GEN-LAST:event_OrderAddBtnActionPerformed

    
    
      
    public void Updated_Table()
{
    try{
        Connection connection = null;
       connection(connection);
        String sql="Select * from ORDERS";
        PreparedStatement preparedstatement=null;
        preparedstatement=connection.prepareStatement(sql);
        ResultSet resultset=null;
        resultset=preparedstatement.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(resultset));
       // int a=(int) Double.parseDouble(dept.getText());
       // pst.setString(1, sname.getText());
       // pst.setString(2, programf.getText());
      //  pst.setInt(3, a);
       // pst.setString(4,sid.getText());
       // pst.executeUpdate();
       // JOptionPane.showMessageDialog(this,"Successfully updated!");
       }
       catch(Exception e)
       {JOptionPane.showMessageDialog(this,e.getMessage());
       
       
       }
       }  
    
    
    private void OrderDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderDeleteBtnActionPerformed

        
        try{
        Connection connection = null;
       connection(connection);
        String sql="delete from ORDERS where O_ID=?";
        PreparedStatement preparedstatement=connection.prepareStatement(sql);
        int a=(int) Double.parseDouble(OrderID.getText());
        preparedstatement.setInt(1, a);
        preparedstatement.executeUpdate();
        JOptionPane.showMessageDialog(this,"Successfully Deleted!");
       }
       catch(Exception e)
       {JOptionPane.showMessageDialog(this,e.getMessage());
       }

        Updated_Table();
        
    }//GEN-LAST:event_OrderDeleteBtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void OrderLogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderLogoutBtnActionPerformed

        new CustomerRecord().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_OrderLogoutBtnActionPerformed

    private void OrderUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderUpdateBtnActionPerformed

        

try{
       Connection connection = null;
       connection(connection);
        String sql="Update ORDERS set P_ID =?,C_ID=?,QUANTITY=?,DATE=?,TIME=?"+" where O_ID =?";
        PreparedStatement preparedstatement=connection.prepareStatement(sql);
        
        
 //pst.setString(1, CID2.getText());
         preparedstatement.setString(1, ProductId.getText());
        preparedstatement.setString(2, CustomerID.getText());
        preparedstatement.setString(3, OrderQuantity.getText());
       // preparedstatement.setString(4, ODATECHOOSER.getText());
         preparedstatement.setString(5, OrderTime.getText());
         int a=(int) Integer.parseInt(OrderID.getText());
        
 preparedstatement.setInt(6, a);
        
        
        
        
   
       preparedstatement.executeUpdate();
        JOptionPane.showMessageDialog(this,"Successfully Updated!");
       }
       catch(Exception e)
       {JOptionPane.showMessageDialog(this,e.getMessage());
       }  
              
       Updated_Table();
        

        // TODO add your handling code here:
    }//GEN-LAST:event_OrderUpdateBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

new CustomerRecord().setVisible(true);
this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdersRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdersRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdersRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdersRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdersRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CustomerID;
    private javax.swing.JLabel Customerid;
    private javax.swing.JButton OrderAddBtn;
    private javax.swing.JLabel OrderDATE;
    private javax.swing.JButton OrderDeleteBtn;
    private javax.swing.JTextField OrderID;
    private javax.swing.JButton OrderLogoutBtn;
    private javax.swing.JLabel OrderQUANTITY;
    private javax.swing.JTextField OrderQuantity;
    private javax.swing.JLabel OrderRecordTitle;
    private javax.swing.JLabel OrderTIME;
    private javax.swing.JScrollPane OrderTable;
    private javax.swing.JTextField OrderTime;
    private javax.swing.JLabel OrderTitle;
    private javax.swing.JButton OrderUpdateBtn;
    private javax.swing.JLabel Orderid;
    private javax.swing.JLabel ProductID;
    private javax.swing.JTextField ProductId;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
