/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframe;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author rimsh
 */
public class ProductsRecord extends javax.swing.JFrame {

    /**
     * Creates new form ProductsJframe
     */
    public ProductsRecord() {
        initComponents();
          Updated_Table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        ProductTitle = new javax.swing.JLabel();
        ProductRecordTitled = new javax.swing.JLabel();
        ProductID = new javax.swing.JLabel();
        ProductCOLOR = new javax.swing.JLabel();
        ProductQUANTITY = new javax.swing.JLabel();
        ProductId = new javax.swing.JTextField();
        ProductColor = new javax.swing.JTextField();
        ProductQuantity = new javax.swing.JTextField();
        ProductAddBtn = new javax.swing.JButton();
        ProductTable = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ProductSIZE = new javax.swing.JLabel();
        ProductSize = new javax.swing.JTextField();
        ProductISSUEDATE = new javax.swing.JLabel();
        ProductBack = new javax.swing.JButton();
        ProductRETURNDATE = new javax.swing.JLabel();
        ProductCATEGORY = new javax.swing.JLabel();
        ProductCategory = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel3.setLayout(null);

        ProductTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ProductTitle.setForeground(new java.awt.Color(0, 102, 102));
        ProductTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProductTitle.setText("Products");
        jPanel3.add(ProductTitle);
        ProductTitle.setBounds(90, 50, 170, 50);

        ProductRecordTitled.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ProductRecordTitled.setForeground(new java.awt.Color(0, 102, 102));
        ProductRecordTitled.setText("Products record");
        jPanel3.add(ProductRecordTitled);
        ProductRecordTitled.setBounds(660, 90, 220, 30);

        ProductID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProductID.setForeground(new java.awt.Color(0, 102, 102));
        ProductID.setText("ID");
        jPanel3.add(ProductID);
        ProductID.setBounds(70, 140, 19, 22);

        ProductCOLOR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProductCOLOR.setForeground(new java.awt.Color(0, 102, 102));
        ProductCOLOR.setText("COLOR");
        jPanel3.add(ProductCOLOR);
        ProductCOLOR.setBounds(40, 240, 90, 22);

        ProductQUANTITY.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProductQUANTITY.setForeground(new java.awt.Color(0, 102, 102));
        ProductQUANTITY.setText("Quantity");
        jPanel3.add(ProductQUANTITY);
        ProductQUANTITY.setBounds(30, 290, 90, 22);
        jPanel3.add(ProductId);
        ProductId.setBounds(140, 140, 170, 30);
        jPanel3.add(ProductColor);
        ProductColor.setBounds(140, 240, 170, 30);

        ProductQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductQuantityActionPerformed(evt);
            }
        });
        jPanel3.add(ProductQuantity);
        ProductQuantity.setBounds(140, 290, 170, 30);

        ProductAddBtn.setBackground(new java.awt.Color(0, 102, 102));
        ProductAddBtn.setForeground(new java.awt.Color(255, 255, 255));
        ProductAddBtn.setText("ADD");
        ProductAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductAddBtnActionPerformed(evt);
            }
        });
        jPanel3.add(ProductAddBtn);
        ProductAddBtn.setBounds(20, 530, 100, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        ProductTable.setViewportView(jTable1);

        jPanel3.add(ProductTable);
        ProductTable.setBounds(490, 160, 550, 400);

        ProductSIZE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProductSIZE.setForeground(new java.awt.Color(0, 102, 102));
        ProductSIZE.setText("SIZE");
        jPanel3.add(ProductSIZE);
        ProductSIZE.setBounds(60, 190, 60, 22);
        jPanel3.add(ProductSize);
        ProductSize.setBounds(140, 190, 170, 30);

        ProductISSUEDATE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProductISSUEDATE.setForeground(new java.awt.Color(0, 102, 102));
        ProductISSUEDATE.setText("ISSUE Date");
        jPanel3.add(ProductISSUEDATE);
        ProductISSUEDATE.setBounds(30, 350, 100, 22);

        ProductBack.setBackground(new java.awt.Color(255, 255, 204));
        ProductBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ProductBack.setForeground(new java.awt.Color(0, 102, 102));
        ProductBack.setText("Back");
        ProductBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductBackActionPerformed(evt);
            }
        });
        jPanel3.add(ProductBack);
        ProductBack.setBounds(1060, 320, 110, 40);

        ProductRETURNDATE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProductRETURNDATE.setForeground(new java.awt.Color(0, 102, 102));
        ProductRETURNDATE.setText("RETURN Date");
        jPanel3.add(ProductRETURNDATE);
        ProductRETURNDATE.setBounds(20, 400, 110, 30);

        ProductCATEGORY.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProductCATEGORY.setForeground(new java.awt.Color(0, 102, 102));
        ProductCATEGORY.setText("CATEGORY");
        jPanel3.add(ProductCATEGORY);
        ProductCATEGORY.setBounds(20, 460, 100, 22);

        ProductCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Butter", "Milk", "Ghee", "Egg", "pelt", "Dripp", "Wools", " " }));
        jPanel3.add(ProductCategory);
        ProductCategory.setBounds(140, 460, 170, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1366, 768);

        setSize(new java.awt.Dimension(1199, 654));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void connection (Connection connection) throws ClassNotFoundException{
        
       // This function is for creating connection with oracle database
        
        try {
            Class.forName("oracle.jdbc.OracleDriver"); // defining the oracle driver 
             connection = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:rimsha", "rimsha", "rimsha"); // establishing connection with user in orcale database
        } 
        
        catch (SQLException ex) { // throwing exception if thus user is not available
            
            Logger.getLogger(ComplainsRecord.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    private void ProductQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductQuantityActionPerformed

    private void ProductAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductAddBtnActionPerformed
  try{
        Connection connection = null;
       connection(connection);
        String sql="insert into PRODUCTS"+"(P_ID,P_SIZE,P_COLOR,P_QUANTITY,ISSUE_DATE,RETURN_DATE,CATEGORY)"+"values(?,?,?,?,?,?,?)";
        PreparedStatement preparedstatement=connection.prepareStatement(sql);
        int a=(int) Integer.parseInt(ProductId.getText());
        
 preparedstatement.setInt(1, a);
 //pst.setString(1, CID2.getText());
        preparedstatement.setString(2, ProductSize.getText());
        preparedstatement.setString(3, ProductColor.getText());
        preparedstatement.setString(4, ProductQuantity.getText());
        //preparedstatement.setString(5, PROISSUEDATE.getText());
         //preparedstatement.setString(6, PROREDATE.getText());
          preparedstatement.setString(7, ProductCategory.getSelectedItem().toString());
        
       preparedstatement.executeUpdate();
         //if(PID.getText().trim().isEmpty() && CID.getText().trim().isEmpty() ){
           // JOptionPane.showMessageDialog(this,"Product key and customer key is mandatory to add!");
        // }else{
        JOptionPane.showMessageDialog(this,"Successfully Inserted!");
         
       }
       catch(Exception e)
       {JOptionPane.showMessageDialog(this,e.getMessage());
       }
    
        
     Updated_Table();
        

    }//GEN-LAST:event_ProductAddBtnActionPerformed

    
     public void Updated_Table()
{
    try{
       Connection connection = null;
       connection(connection);
        String sql="Select * from PRODUCTS";
        PreparedStatement preparedstatement=null;
        preparedstatement=connection.prepareStatement(sql);
        ResultSet resultset=null;
        resultset=preparedstatement.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(resultset));
       // int a=(int) Double.parseDouble(dept.getText());
       // pst.setString(1, sname.getText());
       // pst.setString(2, programf.getText());
      //  pst.setInt(3, a);
       // pst.setString(4,sid.getText());
       // pst.executeUpdate();
       // JOptionPane.showMessageDialog(this,"Successfully updated!");
       }
       catch(Exception e)
       {JOptionPane.showMessageDialog(this,e.getMessage());
       }  
}
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void ProductBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductBackActionPerformed

        new CustomerRecord().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProductBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductsRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductsRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductsRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductsRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductsRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ProductAddBtn;
    private javax.swing.JButton ProductBack;
    private javax.swing.JLabel ProductCATEGORY;
    private javax.swing.JLabel ProductCOLOR;
    private javax.swing.JComboBox<String> ProductCategory;
    private javax.swing.JTextField ProductColor;
    private javax.swing.JLabel ProductID;
    private javax.swing.JLabel ProductISSUEDATE;
    private javax.swing.JTextField ProductId;
    private javax.swing.JLabel ProductQUANTITY;
    private javax.swing.JTextField ProductQuantity;
    private javax.swing.JLabel ProductRETURNDATE;
    private javax.swing.JLabel ProductRecordTitled;
    private javax.swing.JLabel ProductSIZE;
    private javax.swing.JTextField ProductSize;
    private javax.swing.JScrollPane ProductTable;
    private javax.swing.JLabel ProductTitle;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
