/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframe;

import conn.JavaConnectDBROLE;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author rimsh
 */
public class VisitorsRecord extends javax.swing.JFrame {
    Connection conn = null;
    
    String u = null;
    String p = null;
    /**
     * Creates new form VisitorJframe
     */
    public VisitorsRecord() {
        initComponents();
        Updated_Table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        VisitorTitle = new javax.swing.JLabel();
        VisitorRecordTitle = new javax.swing.JLabel();
        VisitorID = new javax.swing.JLabel();
        VisitorNAME = new javax.swing.JLabel();
        VisitorEMAIL = new javax.swing.JLabel();
        VisitorId = new javax.swing.JTextField();
        VisitorName = new javax.swing.JTextField();
        VisitorEmail = new javax.swing.JTextField();
        VisitorAddBtn = new javax.swing.JButton();
        VisitorUpdate = new javax.swing.JButton();
        VisitorTable = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        VisitorCNIC = new javax.swing.JLabel();
        VisitorNIC = new javax.swing.JTextField();
        VisitorPHONE = new javax.swing.JLabel();
        VisitorPhone = new javax.swing.JTextField();
        VisitorLogoutBtn = new javax.swing.JButton();
        VisitorDATE = new javax.swing.JLabel();
        VisitorTIME = new javax.swing.JLabel();
        VisitorTime = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel5.setLayout(null);

        VisitorTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        VisitorTitle.setForeground(new java.awt.Color(0, 102, 102));
        VisitorTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VisitorTitle.setText("Visitor");
        jPanel5.add(VisitorTitle);
        VisitorTitle.setBounds(90, 50, 170, 50);

        VisitorRecordTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        VisitorRecordTitle.setForeground(new java.awt.Color(0, 102, 102));
        VisitorRecordTitle.setText("Visitors Records");
        jPanel5.add(VisitorRecordTitle);
        VisitorRecordTitle.setBounds(660, 90, 220, 30);

        VisitorID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        VisitorID.setForeground(new java.awt.Color(0, 102, 102));
        VisitorID.setText("ID");
        jPanel5.add(VisitorID);
        VisitorID.setBounds(70, 140, 19, 22);

        VisitorNAME.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        VisitorNAME.setForeground(new java.awt.Color(0, 102, 102));
        VisitorNAME.setText("Name");
        jPanel5.add(VisitorNAME);
        VisitorNAME.setBounds(40, 240, 90, 22);

        VisitorEMAIL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        VisitorEMAIL.setForeground(new java.awt.Color(0, 102, 102));
        VisitorEMAIL.setText("Email");
        jPanel5.add(VisitorEMAIL);
        VisitorEMAIL.setBounds(30, 290, 90, 22);
        jPanel5.add(VisitorId);
        VisitorId.setBounds(140, 140, 170, 30);
        jPanel5.add(VisitorName);
        VisitorName.setBounds(140, 240, 170, 30);

        VisitorEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisitorEmailActionPerformed(evt);
            }
        });
        jPanel5.add(VisitorEmail);
        VisitorEmail.setBounds(150, 290, 170, 30);

        VisitorAddBtn.setBackground(new java.awt.Color(0, 102, 102));
        VisitorAddBtn.setForeground(new java.awt.Color(255, 255, 255));
        VisitorAddBtn.setText("ADD");
        VisitorAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisitorAddBtnActionPerformed(evt);
            }
        });
        jPanel5.add(VisitorAddBtn);
        VisitorAddBtn.setBounds(20, 560, 100, 40);

        VisitorUpdate.setBackground(new java.awt.Color(0, 102, 102));
        VisitorUpdate.setForeground(new java.awt.Color(255, 255, 255));
        VisitorUpdate.setText("Update");
        VisitorUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisitorUpdateActionPerformed(evt);
            }
        });
        jPanel5.add(VisitorUpdate);
        VisitorUpdate.setBounds(160, 560, 100, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        VisitorTable.setViewportView(jTable1);

        jPanel5.add(VisitorTable);
        VisitorTable.setBounds(400, 160, 640, 400);

        VisitorCNIC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        VisitorCNIC.setForeground(new java.awt.Color(0, 102, 102));
        VisitorCNIC.setText("CNIC");
        jPanel5.add(VisitorCNIC);
        VisitorCNIC.setBounds(60, 190, 60, 22);
        jPanel5.add(VisitorNIC);
        VisitorNIC.setBounds(140, 190, 170, 30);

        VisitorPHONE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        VisitorPHONE.setForeground(new java.awt.Color(0, 102, 102));
        VisitorPHONE.setText("Phone Number");
        jPanel5.add(VisitorPHONE);
        VisitorPHONE.setBounds(20, 340, 120, 22);
        jPanel5.add(VisitorPhone);
        VisitorPhone.setBounds(150, 340, 170, 30);

        VisitorLogoutBtn.setBackground(new java.awt.Color(255, 255, 204));
        VisitorLogoutBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VisitorLogoutBtn.setForeground(new java.awt.Color(0, 102, 102));
        VisitorLogoutBtn.setText("Logout");
        VisitorLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisitorLogoutBtnActionPerformed(evt);
            }
        });
        jPanel5.add(VisitorLogoutBtn);
        VisitorLogoutBtn.setBounds(1070, 320, 110, 40);

        VisitorDATE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        VisitorDATE.setForeground(new java.awt.Color(0, 102, 102));
        VisitorDATE.setText("DATE");
        jPanel5.add(VisitorDATE);
        VisitorDATE.setBounds(50, 400, 70, 30);

        VisitorTIME.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        VisitorTIME.setForeground(new java.awt.Color(0, 102, 102));
        VisitorTIME.setText("TIME");
        jPanel5.add(VisitorTIME);
        VisitorTIME.setBounds(40, 460, 50, 20);

        VisitorTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisitorTimeActionPerformed(evt);
            }
        });
        jPanel5.add(VisitorTime);
        VisitorTime.setBounds(150, 460, 170, 30);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 1366, 768);

        setSize(new java.awt.Dimension(1203, 687));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     public void connection (Connection connection) throws ClassNotFoundException{
        
       // This function is for creating connection with oracle database
        
        try {
            Class.forName("oracle.jdbc.OracleDriver"); // defining the oracle driver 
             connection = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:rimsha", "rimsha", "rimsha"); // establishing connection with user in orcale database
        } 
        
        catch (SQLException ex) { // throwing exception if thus user is not available
            
            Logger.getLogger(ComplainsRecord.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    
    private void VisitorEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisitorEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VisitorEmailActionPerformed

    
    
      
    public void Updated_Table()
{
    try{
       Connection connection = null;
       connection(connection);
        String sql="Select * from VISITORS";
        PreparedStatement preparedstatement=null;
        preparedstatement=connection.prepareStatement(sql);
        ResultSet resultset=null;
        resultset=preparedstatement.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(resultset));
       
       }
       catch(Exception e)
       {JOptionPane.showMessageDialog(this,e.getMessage());
       }  
}
    
    
    
    
    private void VisitorAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisitorAddBtnActionPerformed

        
         try{
       Connection connection = null;
       connection(connection);
        String sql="insert into VISITORS"+"(V_ID,V_NAME,V_PHONE,V_EMAILADDRESS,V_CNIC,V_TIMING,V_DATE)"+"values(?,?,?,?,?,?,?)";
        PreparedStatement preparedstatement=connection.prepareStatement(sql);
        int a=(int) Integer.parseInt(VisitorId.getText());
        
preparedstatement.setInt(1, a);
 //pst.setString(1, CID2.getText());
        preparedstatement.setString(2, VisitorName.getText());
        preparedstatement.setString(3, VisitorPhone.getText());
        preparedstatement.setString(4, VisitorEmail.getText());
        preparedstatement.setString(5, VisitorNIC.getText());
         preparedstatement.setString(6, VisitorTime.getText());
          //preparedstatement.setString(7, VDATECHOOSER.getText());
        
        preparedstatement.executeUpdate();
        JOptionPane.showMessageDialog(this,"Successfully Inserted!");
       }
       catch(Exception e)
       {JOptionPane.showMessageDialog(this,e.getMessage());
       }
    
        
     Updated_Table();
        
        
        
    }//GEN-LAST:event_VisitorAddBtnActionPerformed

    private void VisitorUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisitorUpdateActionPerformed

         try{
      Connection connection = null;
       connection(connection);
        String sql="Update VISITORS set V_NAME =?,V_PHONE=?,V_EMAILADDRESS=?,V_CNIC=?,V_TIMING=?,V_DATE=?"+" where V_ID =?";
        PreparedStatement preparedstatement=connection.prepareStatement(sql);
        
        
 //pst.setString(1, CID2.getText());
        preparedstatement.setString(1, VisitorName.getText());
        preparedstatement.setString(2, VisitorPhone.getText());
        preparedstatement.setString(3, VisitorEmail.getText());
        preparedstatement.setString(4, VisitorNIC.getText());
         preparedstatement.setString(5, VisitorTime.getText());
         // preparedstatement.setString(6, VDATECHOOSER.getText());
         int a=(int) Integer.parseInt(VisitorId.getText());
        
preparedstatement.setInt(7, a);
        
        
        
        
   
        preparedstatement.executeUpdate();
        JOptionPane.showMessageDialog(this,"Successfully Updated!");
       }
       catch(Exception e)
       {JOptionPane.showMessageDialog(this,e.getMessage());
       }  
              
       Updated_Table();
        
        
    }//GEN-LAST:event_VisitorUpdateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

       
    }//GEN-LAST:event_jTable1MouseClicked

    private void VisitorLogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisitorLogoutBtnActionPerformed

        new DistributorVisitorLogin().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_VisitorLogoutBtnActionPerformed

    private void VisitorTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisitorTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VisitorTimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisitorsRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisitorsRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisitorsRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisitorsRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisitorsRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VisitorAddBtn;
    private javax.swing.JLabel VisitorCNIC;
    private javax.swing.JLabel VisitorDATE;
    private javax.swing.JLabel VisitorEMAIL;
    private javax.swing.JTextField VisitorEmail;
    private javax.swing.JLabel VisitorID;
    private javax.swing.JTextField VisitorId;
    private javax.swing.JButton VisitorLogoutBtn;
    private javax.swing.JLabel VisitorNAME;
    private javax.swing.JTextField VisitorNIC;
    private javax.swing.JTextField VisitorName;
    private javax.swing.JLabel VisitorPHONE;
    private javax.swing.JTextField VisitorPhone;
    private javax.swing.JLabel VisitorRecordTitle;
    private javax.swing.JLabel VisitorTIME;
    private javax.swing.JScrollPane VisitorTable;
    private javax.swing.JTextField VisitorTime;
    private javax.swing.JLabel VisitorTitle;
    private javax.swing.JButton VisitorUpdate;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
