/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conn;

import Jframe.CustomerRecord;
import Jframe.DistributorVisitorLogin;
import Jframe.SubUsersRecord;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author rimsh
 */
public class ManagerCustomerLogin extends javax.swing.JFrame {
    
    Connection connection = null;
    OraclePreparedStatement preparedstatement = null;
    OracleResultSet resultset = null;

    /**
     * Creates new form MClogin
     */
    public ManagerCustomerLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ManagerUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ManagerLoginBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ManagerLoginTitle = new javax.swing.JLabel();
        CustomerLoginTitle = new javax.swing.JLabel();
        ManagerPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CustomerUsername = new javax.swing.JTextField();
        CustomerLoginBtn = new javax.swing.JButton();
        LoginAsOtherBtn = new javax.swing.JButton();
        CustomerPassord = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(ManagerUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 190, 40));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 60, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        ManagerLoginBtn.setBackground(new java.awt.Color(255, 255, 255));
        ManagerLoginBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ManagerLoginBtn.setForeground(new java.awt.Color(0, 102, 102));
        ManagerLoginBtn.setText("LOGIN");
        ManagerLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerLoginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ManagerLoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 140, 50));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManagerLoginTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ManagerLoginTitle.setForeground(new java.awt.Color(255, 255, 255));
        ManagerLoginTitle.setText("Manager Login");
        jPanel2.add(ManagerLoginTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        CustomerLoginTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        CustomerLoginTitle.setForeground(new java.awt.Color(255, 255, 255));
        CustomerLoginTitle.setText("Customer Login");
        jPanel2.add(CustomerLoginTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 90));
        jPanel1.add(ManagerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 190, 40));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, -1, -1));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, -1, -1));
        jPanel1.add(CustomerUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 190, 40));

        CustomerLoginBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CustomerLoginBtn.setForeground(new java.awt.Color(0, 102, 102));
        CustomerLoginBtn.setText("Login");
        CustomerLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerLoginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CustomerLoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, 130, 50));

        LoginAsOtherBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LoginAsOtherBtn.setForeground(new java.awt.Color(0, 102, 102));
        LoginAsOtherBtn.setText("Login as others");
        LoginAsOtherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginAsOtherBtnActionPerformed(evt);
            }
        });
        jPanel1.add(LoginAsOtherBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 160, 40));
        jPanel1.add(CustomerPassord, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 190, 40));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -10, 1010, 530);

        setSize(new java.awt.Dimension(939, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ManagerLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerLoginBtnActionPerformed
        // TODO add your handling code here:
       connection = JavaConnectDB.ConnectDB();
        
        try{
            String sql = "select * from MLogin where username = ? and password = ? ";
           preparedstatement = (OraclePreparedStatement) connection.prepareStatement(sql);
            preparedstatement.setString(1,ManagerUsername.getText());
           preparedstatement.setString(2,ManagerPassword.getText());
           // JOptionPane.showMessageDialog(null," exeqution se pehle");
            resultset = (OracleResultSet) preparedstatement.executeQuery();
           // JOptionPane.showMessageDialog(null," exeqution se pehle");
            if(resultset.next())
            {
               JOptionPane.showMessageDialog(null," login successfuly");
             
               new SubUsersRecord().setVisible(true);
               this.dispose();
            }
            else
            {
                 JOptionPane.showMessageDialog(null," invalid login");
            }
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_ManagerLoginBtnActionPerformed

    private void CustomerLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerLoginBtnActionPerformed


 connection = JavaConnectDB.ConnectDB();
        
        try{
            String sql = "select * from CLogin where username = ? and password = ? ";
            preparedstatement = (OraclePreparedStatement) connection.prepareStatement(sql);
            preparedstatement.setString(1,CustomerUsername.getText());
            preparedstatement.setString(2,CustomerPassord.getText());
            //JOptionPane.showMessageDialog(null," exeqution se pehle");
            resultset = (OracleResultSet) preparedstatement.executeQuery();
           // JOptionPane.showMessageDialog(null," exeqution se pehle");
            if(resultset.next())
            {
               JOptionPane.showMessageDialog(null," login successfuly");
               new CustomerRecord().setVisible(true);
               this.dispose();
            }
            else
            {
                 JOptionPane.showMessageDialog(null," invalid login");
            }
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }



        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerLoginBtnActionPerformed

    private void LoginAsOtherBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginAsOtherBtnActionPerformed
        // TODO add your handling code here:
        
        new DistributorVisitorLogin().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_LoginAsOtherBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerCustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerCustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerCustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerCustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerCustomerLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CustomerLoginBtn;
    private javax.swing.JLabel CustomerLoginTitle;
    private javax.swing.JPasswordField CustomerPassord;
    private javax.swing.JTextField CustomerUsername;
    private javax.swing.JButton LoginAsOtherBtn;
    private javax.swing.JButton ManagerLoginBtn;
    private javax.swing.JLabel ManagerLoginTitle;
    private javax.swing.JPasswordField ManagerPassword;
    private javax.swing.JTextField ManagerUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
